

###

POST http://localhost:8080/

###

GET http://localhost:8080/api/users

###
PUT http://localhost:8080/api/users/:uid
###


###
GET  http://localhost:8080/api/products/
###
POST http://localhost:8080/api/products/



//productos
###
POST http://localhost:8080/api/products
Content-Type: application/json

{
       
    "title":"producto 1",
    "description":"description 1",
    "price":"100",
    "img":"ruta img",
    "code":"04",
    "stock" :"10"
    
}

###
PUT http://localhost:8080/api/products/1
Content-Type: application/json

{
       
    "title":"producto 1",
    "description":"description 1",
    "price":"100",
    "img":"ruta img",
    "code":"04",
    "stock" :"10"
    
}

###
DELETE http://localhost:8080/api/products/1

//Carrito
###
GET  http://localhost:8080/api/carts/

###
GET  http://localhost:8080/api/carts/4

###
POST http://localhost:8080/api/carts/
Content-Type: application/json

{
       
    "title":"producto 12",
    "description":"description 12",
    "price":"100",
    "img":"ruta img",
    "code":"13",
    "stock" :"10"
    
}

###
POST http://localhost:8080/api/carts/
Content-Type: application/json

{
       
    "title":"producto 15",
    "description":"description 15",
    "price":"100",
    "img":"ruta img",
    "code":"15",
    "stock" :"10"
    
}

