
//USUARIOS
###

POST http://localhost:8080/

###

GET http://localhost:8080/api/users

###
PUT http://localhost:8080/api/users/:uid
###

//PRODUCTOS
###
GET  http://localhost:8080/api/products/4
###

###
POST http://localhost:8080/api/products
Content-Type: application/json

{
       
    "title":"producto 12",
    "description":"description 12",
    "price":"100",
    "img":"ruta img",
    "code":"19",
    "stock" :"50"
    
}

###
PUT http://localhost:8080/api/products/8
Content-Type: application/json

{
       
    "title":"producto 1",
    "description":"description 1",
    "price":"100",
    "img":"ruta img",
    "code":"04",
    "stock" :"10"
    
}

###
DELETE http://localhost:8080/api/products/7

//CARRITO
###
GET  http://localhost:8080/api/carts/10


###
POST http://localhost:8080/api/carts/
Content-Type: application/json

{     
    "title":"carrito 14",
    "price":"100",
    "code":"14"   
}

###
POST http://localhost:8080/api/carts/
Content-Type: application/json

{
    "title":"producto 15", 
    "price":"100",
    "code":"15"  
}


//router.post('/:cid/product/:pid'